### ISSUE TITLE
Binaries in the repos

### ISSUE THREAD

**Issue by duncantl** [aviralg/r#1]
Hi
Nice work.  When we clone the repos and invoked make, we got errors about ../../....../R.h and install.  There are binaries in the repos so make thinks things are up to date and so doesn't build for the architecture.  A quick make clean and ./configure && make  sorts things out.

**Comment by aviralg** [comment]
Hi,

Thanks. I should have done `make clean` before committing. I have corrected the issue with commit f9bbd971f6de5d4aafeac6fecea18c587b82ac7f
